- source/UnivalenceFromScratch.lagda
Hi, I'm pretty new to Univalence, and most of my experience of MLTT consists of using Idris as a theorem prover for various toy examples. 
Possibly the variable **y** of type **X** could have a different name, eg **x'** or **x_1**, to avoid confusion with **y** of type **Y** ?
> typos in Univalence from Scratch

- source/UF-FunExt-from-Naive-FunExt-alternate.lagda
The proof that naive function extensionality implies full function extensionality goes via the fact that if f is an equivalence, then so is precomposition with f. I've abstracted that argument here.
This means that the following are logically equivalent:
1. Naive function extensionality;
2. Precomposition with an equivalence is an equivalence;
3. Function extensionality;
4. Propositions are closed under Pi,
5. Singletons are closed under Pi.
The last 4 are propositions, so are equivalent. Should I add a file summarizing this?
> Added modification of naive-funext-to-funext

- source/Frame.lagda
- source/index.lagda
I have used combinators for Ω in this development that I defined inside the `Frame` module. Instead of adding such ad-hoc definitions, we should first address #43 in a separate PR in my opinion.
> Add a definition of frames

- .github/workflows/main.yml
This should fix the failing run of the Agda action. The problem is that it defaults to running Agda with the `--safe` flag which doesn't work for `AllModulesIndex.lagda`. This PR disables the `--safe` flag.
> Run the Agda action without the `--safe` flag

- source/Frame.lagda
- source/UF-Subsingleton-Combinators.lagda
- source/index.lagda
_This PR fixes #43._
I have added subsingleton combinators as discussed in #43. Because different combinators require different assumptions, I have separated these into their own submodules. To give an example:
```agda
module Universal (fe : Fun-Ext) where
∀[∶]-syntax : (I : 𝓤 ̇) → (I → Ω 𝓥) → Ω (𝓤 ⊔ 𝓥)
∀[∶]-syntax I P = ((i : I) → P i holds) , γ
where
γ : is-prop ((i : I) → P i holds)
γ = Π-is-prop fe (holds-is-prop ∘ P)
∀[]-syntax : {I : 𝓤 ̇} → (I → Ω 𝓥) → Ω (𝓤 ⊔ 𝓥)
∀[]-syntax {I = I} P = ∀[∶]-syntax I P
infix 3 ∀[∶]-syntax
infix 3 ∀[]-syntax
syntax ∀[∶]-syntax I (λ i → e) = ∀[ i ∶ I ] e
syntax ∀[]-syntax    (λ i → e) = ∀[ i ] e
```
It will usually be the case that _all_ of these will be imported, so I also added a submodule called `AllCombinators` (that dependends on both propositional …
> Add combinators for Ω (addresses #43)

- source/Frame.lagda
- source/InitialFrame.lagda
- source/UF-Subsingleton-Combinators.lagda
I finally got around to addressing issue #53. As discussed, the universal and existential quantification syntaxes have been changed to use `Ɐ` (`U+2C6F`) and `Ǝ` (`U+018E`). Unfortunately, there doesn't seem to be an easy way of typing these characters in emacs.
----
Closes #53.
----
> Update the ∀ and ∃ syntaxes

- source/CompactRegular.lagda
- source/Frame.lagda
- source/InitialFrame.lagda
- source/UF-Subsingleton-Combinators.lagda
- source/index.lagda
This PR contains some basic proofs that will be useful once I start porting the patch frame to `TypeTopology`. Here is a short summary of the developments added in this PR:
1. Definitions of the well inside and way below relations.
1. Well inside implies below.
1. The fact that being a clopen is a proposition, even though the well inside relation in general is not a proposition (I added a counterexample using the initial frame).
1. Compact opens are closed under binary joins in any frame.
1. Scott-continuity of the closed nucleus.
1. The fact that well inside implies way below in any compact frame, and
- as a corollary of this: clopens are compact in any compact frame.
> Some developments related to well inside and way below

- source/FreeJoinSemiLattice.lagda
- source/FreeSupLattice.lagda
- source/JoinSemiLattices.lagda
- source/UF-Classifiers.lagda
- source/UF-Powerset-Fin.lagda
- source/UF-Powerset.lagda
- source/index.lagda
1. Created a new file on Kuratowski finite subsets called `UF-Powerset-Fin.lagda`. In particular, it contains a proof that the type of Kuratowski finite subsets of a set X is equivalent to the image of the canonical map List X → 𝓟 X.
1. Added some basic constructions to `UF-Powerset.lagda`, e.g. the total space of a subset, notation for singleton subsets, binary intersections/unions, etc.
1. Cleaned up `FreeJoinSemiLattice.lagda` and `FreeSupLattice.lagda`. In particular:
- Both files now import the total space of a subset, singletons, unions, etc. from `UF-Powerset.lagda`.
- Factored out the definition of a join-semilattice and put this in `JoinSemiLattices.lagda`, so it could be used in `UF-Powerset-Fin.lagda`.
- Moved the basic lemmas about Kuratowski finite subsets from …
> New file on Kuratowski finite subsets

- source/UF-Quotient.lagda
- source/UF-Size.lagda
As suggested here: https://github.com/martinescardo/TypeTopology/pull/77#issuecomment-1068240851
> Move definition of small images to UF-Size

- source/Locales/CompactRegular.lagda
- source/Locales/Frame.lagda
**Fixed version of draft PR #99.**
---
Let `L` and `M` be two frames and let `h : | L | → | M |` be a function. Function `h` is said to satisfy the **continuity condition** if *for every `x : L`, compact `b : M` with `b ≤ h(x)`, there is some compact `a : L` such that `a ≤ x` and `b ≤ h(a)`*.
This PR adds the proofs of the following lemmas:
1. Given frames `L` and `M`, with `M` spectral, any monotone function `h : ∣ L ∣ → ∣ M ∣` satisfying the continuity condition is Scott-continuous. (Called `characterisation-of-continuity`.)
1. We now prove the converse: given frames `L` and `M`, with `L` spectral, any Scott-continuous function `h : ∣ L ∣ → ∣ M ∣` satisfies the continuity condition. (Called `characterisation-of-continuity-op`.)
1. As a corollary of (2): given any spectral frame `F`, for …
> Add some lemmas needed for the universal property

- source/Categories/Adjunction.lagda
- source/Categories/Category.lagda
- source/Categories/Functor.lagda
- source/Categories/NaturalTransformation.lagda
- source/Duploids/DeductiveSystem.lagda
- source/Duploids/Depolarization.lagda
- source/Duploids/Duploid.lagda
- source/Duploids/Preduploid.lagda
When Σ-types are used, Agda is for some reason unable to infer a lot of implicit parameters; this becomes too unwieldy when doing category theory (e.g. natural transformations). I do not fully understand what it is about Σ-types that causes this information-loss, but switching to records solves the problem. In each case that I introduced a record, I proved it equivalent to a Σ-type. This is necessary when characterizing path spaces.
In the course of making this change, it was necessary to define the associators and unitors for functor composition. I think this is because when records are used instead of sums, various type dependencies end up involving the entire data of a functor, rather than just its action on objects and morphisms. (I still don't fully understand why that is, btw — but …
> [Categories] Better type inference; add associators and unitors

- source/UF/FunExt.lagda
- source/UF/IdentitySystems.lagda
Does something like this already exist in the library, or is this worth including? This introduces "identity systems" from Egbert's book, which are like custom implementations of the based identity type; and "dependent identity systems", which are displayed over an existing identity system. By composing these, it is possible to characterize somewhat complex identity types.
> add 'identity systems', useful for characterizing path spaces

- source/DedekindReals/Extension.lagda
- source/Rationals/Abs.lagda
- source/Rationals/Order.lagda
This pull request fixes the typo at the top of the extension file, and adds one more example (absolute value) of a uniformly continuous extension function extended from rationals to reals.
> Fix typo in extension file, add reals abs function

- source/Integers/Abs.lagda
- source/Integers/Order.lagda
- source/Naturals/AbsoluteDifference.lagda
- source/Naturals/Order.lagda
On Dr. Escardo's invitation from mathstodon, I am contributing my proof of the triangle inequality in the Naturals and the Integers. In the Naturals, I define a new Absolute Difference operation and prove some elementary lemmas. I then add associated lemmas for Absolute Difference to the Natural Order lemmas, proving the triangle inequality on the way for the naturals under this operation. I then prove some useful lemmas for Absolute Value in the Integers related to this new operation, and conclude by proving the triangle inequality in the Integer Order file (for both abs and adding a translated lemma to absZ for convenience).
> triangle inequality for naturals and integers

- source/Notation/Order.lagda
I'd like to propose a new notation type class to generalize Reasoning Chain notation. All partial orders have transitivity, and as I'm sure anyone who has spent time coding an order module might agree, it would be extremely useful to have reasoning chain notation similar to the one we use for the identity type to make proofs neat and tidy.
The definition I propose reads as follows:
```
record Reflexive-Order {𝓤} (X : 𝓤 ̇ )
(_R_ : X → X → 𝓤 ̇ ) : 𝓤 ̇  where
field
_▨ : (x : X) → x R x
infix 1 _▨
open Reflexive-Order {{...}} public
record Reasoning-Chain {𝓤} {𝓥} {𝓦} {𝓣} {𝓧 : Universe}
(X : 𝓤 ̇ ) (Y : 𝓥 ̇ ) (Z : 𝓦 ̇ )
(_R₁_ : X → Y → 𝓦 ̇ )
(_R₂_ : Y → Z → 𝓣 ̇ )
(_R₃_ : X → Z → 𝓧 ̇ ) : (𝓤 ⊔ 𝓥 ⊔ 𝓦 ⊔ 𝓣 ⊔ 𝓧)⁺ ̇  where
field
_⸴_⊢_ : (x : X) {y : Y} {z : Z} → x R₁ y → y R₂ z → x R₃ z
infixr 0 _⸴_⊢_ …
```
> Suggest general reasoning chain notation

- source/UF/Base.lagda
- source/WildCategories/Base.lagda
- source/WildCategories/Cones.lagda
- source/WildCategories/Idempotents.lagda
- source/WildCategories/index.lagda
- source/index.lagda
I have been formalizing some arguments due to [Mike Shulman](https://homotopytypetheory.org/2018/11/26/impredicative-encodings-part-3/). The idea is to deduce that a wild category has an initial object (in the sense of certain contractible hom spaces) when it possesses an incoherent cone `\Delta I ---> Id` over its identity functor, whose "generic" component at `I` itself splits as `(I --> I) == (I --> J --> I)`. In particular, `J` is the initial object.
Furthermore, if you have a "semicoherent" cone (this semicoherence is basically the next dimension of naturality wrt. binary composition), then its generic component is a quasi-idempotent in the sense of Shulman's paper on idempotents in ITT. Therefore, if quasi-idempotents split, you can use this to find an initial object.
> Idempotents in wild category theory

- CONTRIBUTING.md
Document two more conventions:
1. Sorting import lines.
1. Indentation for type signatures that go over the character limit.
> Document two more conventions

- README.md
- source/Modal/SigmaClosedReflectiveSubuniverse.lagda
- source/Modal/Subuniverse.lagda
- source/Modal/index.lagda
At the moment the library has definitions of subuniverse and reflective subuniverse. In order to get one of the 3 definitions of modalities given by Rijke, Shulman, Spitters, Modalities in HoTT, we have to add an extra condition to reflective subuniverse - that it is sigma closed. This patch adds the definition and a proof of the induction principle for sigma closed subuniverses.
> Add sigma closed subuniverses

- source/TypeTopology/AbsolutenessOfCompactness.lagda
- source/TypeTopology/index.lagda
This is a proof that compactness is upwards absolute with respect to reflective subuniverses. That is, if a type in a reflective subuniverse is compact relative to the internal logic of the subuniverse, then it is actually compact. This can be seen as a generalisation of the result that products of compact types indexed by a proposition are compact (see comments in file for more details).
This branch also adds the file to the index file in TypeTopology.
> Absoluteness of compactness

- source/Modal/Open.lagda
- source/TypeTopology/AbsolutenessOfCompactness.lagda
- source/TypeTopology/AbsolutenessOfCompactnessExample.lagda
- source/TypeTopology/index.lagda
Here is version 2 of the absoluteness of compactness. The main addition is using the open modality to derive another proof of prop-tychonoff. I had to do this as a separate file, since the modality is a module parameter to AbsolutenessOfCompactness, so in order to work with a specific modality (the open modality on a proposition P) it's necessary to pass it as a module parameter from a separate file.
I also added some explanation in the comments about an example from realizability of downwards absoluteness failing.
> Absoluteness of compactness example

- source/DomainTheory/BasesAndContinuity/Bases.lagda
- source/DomainTheory/BasesAndContinuity/ScottDomain.lagda
- source/DomainTheory/Lifting/LiftingSet.lagda
- source/DomainTheory/Topology/ScottTopology.lagda
- source/DomainTheory/Topology/ScottTopologyProperties.lagda
- source/DomainTheory/index.lagda
- source/Locales/ScottLocale/ScottLocalesOfAlgebraicDcpos.lagda
@tomdjong requested that I break PR #217 into smaller PRs — which is quite reasonable given how large that PR had gotten. This is the first in a series of PRs breaking up PR #217.
It adds three things:
1. The definition of the notion of [Scott domain](https://ayberkt.github.io/mathematical-forest/axt-000J.xml).
2. A version of `𝓛-DCPO` that gives an intrinsically locally small dcpo. This is kind of a hack, but it’s very conventient for me at the moment.
3. A module, called `Topology.ScottTopologyProperties`, in which some properties of the Scott topology of a dcpo is proved.
There are also a bunch of other minor additions.
By the way, let me also note that there is a well-principled way of breaking up a large PR into smaller PRs: one can create a new branch and then automatically …
> Step 1 of PR #217

- source/Locales/ContinuousMap/FrameHomomorphism-Definition.lagda
- source/Locales/LawsonLocale/CompactElementsOfPoint.lagda
- source/Locales/LawsonLocale/SharpElementsCoincideWithSpectralPoints.lagda
- source/Locales/Point/SpectralPoint-Definition.lagda
- source/Locales/TerminalLocale/Properties.lagda
- source/Locales/index.lagda
- source/UF/Logic.lagda
This pull request adds a new module, named `Locales.LawsonLocale.SharpElementsCoincideWithSpectralPoints`, containing the following new result:
---
Given any Scott domain $\mathcal{D}$ (satisfying the usual decidability condition), the type of _sharp elements_ of $\mathcal{D}$ is equivalent to the type of _spectral points_ of the Scott locale of $\mathcal{D}$.
---
The proof is at the end of the mentioned module and is called `♯𝓓-equivalent-to-spectral-points-of-Scott⦅𝓓⦆`.
> Prove that the sharp elements of a Scott domain coincide with the spectral points of its Scott locale

- source/Ordinals/Maps.lagda
- source/Ordinals/Notions.lagda
- source/Ordinals/OrdinalOfOrdinals.lagda
@fredrikNordvallForsberg and I showed that
```
Given simulations
f : α ⊴ γ and g : β ⊴ γ
and points a : α and b : β we have
f a ≼ g b   ⇔   α ↓ a ⊴ β ↓ b,
and
f a ＝ g b   ⇔   α ↓ a ≃ₒ β ↓ b.
```
This is preliminary work for a future PR on ordinal exponentation. 
In the process, we generalized some universe levels in existing constructions, i.e. we allowed the carriers of ordinals α and β to be in different universes.
> Lemma about simulations and initial segments of ordinals

- source/InjectiveTypes/CounterExamples.lagda
@martinescardo I implemented this morning's TODO and left an optional one.
> A type with a nontrivial apartness relation cannot be injective unless WEM holds.

- source/Locales/LawsonLocale/PointsOfPatch.lagda
- source/Locales/Point/SpectralPoint-Definition.lagda
- source/Locales/Spectrality/SpectralityOfOmega.lagda
- source/Locales/StoneImpliesSpectral.lagda
- source/Locales/TerminalLocale/Properties.lagda
- source/Locales/index.lagda
This module adds a proof of the following theorem:
- For every Scott domain 𝓓 (satisfying the decidability condition), the points of Patch(Scott(𝓓)) are in bijection with the sharp elements of 𝓓.
> Prove equivalence between sharp elements and the points of patch

- source/UF/Choice.lagda
- source/UF/ClassicalLogic.lagda
- source/UF/EquivalenceExamples.lagda
- source/UF/FunExt-Properties.lagda
- source/UF/FunExt-from-Naive-FunExt.lagda
- source/UF/H-Levels.lagda
- source/UF/HLevels.lagda
- source/UF/Knapp-UA.lagda
- source/UF/NotNotStablePropositions.lagda
- source/UF/Powerset-Fin.lagda
- source/UF/Powerset-Resizing.lagda
- source/UF/PreSIP-Examples.lagda
- source/UF/PreUnivalence.lagda
- source/UF/PropTrunc-Variation.lagda
- source/UF/Retracts-FunExt.lagda
- source/UF/SIP-Examples.lagda
- source/UF/Section-Embedding.lagda
- source/UF/SetTrunc.lagda
- source/UF/Sets.lagda
- source/UF/SmallnessProperties.lagda
- source/UF/StructureIdentityPrinciple.lagda
- source/UF/SubtypeClassifier-Properties.lagda
- source/UF/UA-FunExt.lagda
- source/imports.sh
- source/rm-imports-dir.sh
- source/rm-imports.sh
The removal of unused imports in this PR was achieved with `./rm-imports-dir.sh UF/`.
All of this is quite rudimentary.
> Unused imports

- source/Locales/DiscreteLocale/Basis.lagda
- source/Locales/DiscreteLocale/Definition.lagda
- source/Locales/index.lagda
This PR does a couple of things:
1. It constructs a basis for the discrete locale in a new module called `DiscreteLocale.Basis`.
2. Cleans up the modules related to the discrete locale in `Locales.index`.
3. Does some additional cleaning related to the discrete locale.
This is motivated by the presentation in the thesis.
> Construct a basis for the discrete locale and clean up discrete locale modules

- source/Unsafe/CoNat-Equiv.lagda
- source/Unsafe/index.lagda
@martinescardo  Is this what you wanted in #309 ?
> Equivalence of conatural types

- README.md
- source/UF/FunExt-Properties.lagda
- source/UF/PreUnivalence.lagda
This PR contains two unrelated things (sorry):
- A statement of Fredrik Bakke's "strong preunivalence axiom", a proof that strong preunivalence implies preunivalence, and a proof that preunivalence + funext implies strong preunivalence.
- A statement of "equivalence extensionality" (identity of equivalences is pointwise equality of the underlying functions) and a proof that equivalence extensionality implies function extensionality.
> Strong preunivalence and equivalence extensionality

- README.md
- source/MLTT/Plus.lagda
- source/TypeTopology/CompactTypes.lagda
- source/UF/ImageAndSurjection.lagda
This PR gives a straightforward generalization of the proposition that compact types are closed under covers that doesn't need function extensionality or propositional truncations.
Apologies if I'm not following best practices; any advice is appreciated!
> Compact types are closed under dense covers

- README.md
- source/Higgs/AutomorphismsOfOmegaWEM.lagda
- source/Higgs/UntruncatedAtMostTwo.lagda
- source/Higgs/index.lagda
- source/UF/DiscreteAndSeparated.lagda
The lemma used to prove this probably could serve to be moved somewhere else. I think a section for different notions of cardinality comparisons would be nice.
It implies also that a truncated form of the has-a-repetition would be very reasonable.
The proof is novel as far as I know, although the idea is inspired by Diaconescu's theorem. When we have a function whose domain is extensional, we can force it to make commitments on things which we later learn are equal.
> Prove equivalence of untruncated at-most-two lemma for Aut Omega and EM for Aut Omega

- source/UF/Size.lagda
I also removed an inlined equivalence argument from a special case of my lemma, since it was later added to the library.
> Subtypes are locally small (wrt reference universe)
