martinescardo/TypeTopology

source/LiftingSet.lagda
source/UF-Base.lagda
source/UF-Subsingletons.lagda

Also proved that the product of two sets is a set (see UF-Subsingletons).

The lifting of a set is a set

---

source/UF-Classifiers.lagda

Generalisation inspired by your proof in the lecture notes.

Small generalisation

---

source/UF-Size.lagda

Resizing of has-size

---

source/UF-Base.lagda
source/UF-Embeddings.lagda
source/UF-EquivalenceExamples.lagda
source/UF-Retracts.lagda

Most important addition: some equivalences of fibers.

More general additions

---

source/UF-ImageAndSurjection.lagda
source/UF-PropTrunc.lagda

Remove some comments

---

.github/workflows/main.yml
source/AllModulesIndex.lagda

Fix failing workflow (fixes #54)

---

source/Negation.lagda
source/WellOrderingTaboo.lagda
source/index.lagda

Based on two constructions by Andrew Swan

Well ordering taboo

---

source/Frame.lagda
source/List.lagda
source/UF-Subsingleton-Combinators.lagda

This PR implements the directification of a frame basis as discussed last Monday.

Define frame bases and implement their directification

---

source/DecidableAndDetachable.lagda

As discussed in Agda Club on Friday 29 October.

2 classifies decidable subsets

---

source/Frame.lagda

This PR implements a name change that was [requested](https://github.com/martinescardo/TypeTopology/pull/63#issuecomment-933560482) a while ago and does some cosmetic cleaning.

Name change and some cleaning

---

source/WellOrderingTaboo.lagda

As suggested by @martinescardo.

Simpler formulation of extensionality for minimal elements

---

source/UF-Quotient.lagda

As discussed yesterday and over the weekend.

Small images yield small quotients

---

source/UF-Quotient.lagda
source/UF-Size.lagda

We can discuss this PR tomorrow.

Small set quotients yield small images of maps to locally small sets

---

source/OrdinalOfOrdinalsSuprema.lagda
source/OrdinalTaboos.lagda
source/OrdinalsWellOrderArithmetic.lagda

Excluded middle follows from either of the following classically true assertions:
- every discrete ordinal is trichotomous;
- the supremum of every discretely-indexed family of trichotomous ordinals is discrete.

Taboos involving ordinals, discreteness and trichotomy

---

source/Ordinals/Indecomposable.lagda

Add comments on indecomposability of sup-lattices

---

source/Modal/Homotopy.lagda
source/Modal/ReflectiveSubuniverse.lagda
source/Modal/Subuniverse.lagda
source/Modal/index.lagda
source/UF/FunExt.lagda
source/Utilities/PairFun.lagda

I have started filling up the "blackboard" with some basics of subuniverses, reflective subuniverses, etc. Not much here yet, but I'll be working on this recreationally over the next few weeks probably. No need to merge right away, but I thought I'd open a draft pull request now in case there is any feedback and suggestions, etc.

Reflective Subuniverses

---

source/Modal/index.lagda

- Improve readability of the doi url of "Modalities in homotopy type theory"
- Add arXiv link to Egbert's thesis.

Improvements to urls in Modal/Index

---

source/DomainTheory/ScottModelOfPCF/ScottModelOfPCF.lagda

As suggested by Andrej Bauer during my viva.

Add examples of computing with the Scott model of PCF

---

source/Dyadics/Addition.lagda
source/Dyadics/Multiplication.lagda
source/Dyadics/Negation.lagda
source/Dyadics/Order.lagda
source/Dyadics/Type.lagda
source/Integers/Exponentiation.lagda
source/Integers/index.lagda
source/Naturals/Exponentiation.lagda
source/Naturals/Parity.lagda
source/Naturals/index.lagda

This branch implements the requested changes to the previous pull request: https://github.com/martinescardo/TypeTopology/pull/118
The two files which implement exponentiation are both renamed as suggested. 
I have made many formatting changes, ensuring that every line is 80 characters or less.

Fulfil requests

---

source/Coslice/Hom.lagda
source/Coslice/Type.lagda
source/Coslice/index.lagda
source/UF/IdentitySystems.lagda
source/UF/SemistrictIdentity.lagda
source/UF/index.lagda

I'm starting to formalize *coslices*. I know there is already a module for slices; the thing I wanted to prove this week, though, was a little different. I wanted to characterize the path space of functions in the coslice. This is just a start, I will also eventually characterize path spaces of objects (as in the slice library), and harmonize the coslice and slice modules. But what I have here is I guess ready to be looked at.
This PR also improves the identity-systems library to be more flexible wrt. universes; this comes at the cost of the type of identity systems being very large.

characterize path spaces of morphisms in the coslice

---

source/Various/RootsOfBooleanFunctions.lagda

Here is a proof of `ε-formula' n` and `ε-formula n` being equals, and the proof of  `ε-formula' n` correctness via transport

Solving RootsOfBooleanFunctions challenge

---

source/Locales/CompactRegular.lagda
source/Locales/InitialFrame.lagda

Resolves #69 by implementing the change discussed there.

Refactor the `InitialFrame` module as to use propositional extensionality instead of full univalence (resolves #69)

---

README.md

Add publications

---

source/Various/RootsOfBooleanFunctions.lagda

I did the correction you suggested, and added the proof ε is the infimum. But i'm not sure where the proof should go, as it feel a little stranded at the end of the file

Typos and infimum proof

---

source/CantorSchroederBernstein/CSB.lagda
source/EffectfulForcing/InternalWithoutOracle.lagda
source/Ordinals/Notions.lagda
source/Various/RootsOfBooleanFunctions.lagda

Making some progress on the internal correctness.
Bruno and Ayberk mostly told Vincent what to type.

Internal correctness

---

source/Dominance/Definition.lagda
source/Dominance/Lifting.lagda

I'm just opening this draft PR to track my work on dominances, lifting, etc. I'll let you know when it is ready for review.

Playing with dominances

---

source/TypeTopology/TotallySeparated.lagda

Update indentation sizes in some places as to ensure compliance with the conventions set in the [contribution guidelines](https://github.com/martinescardo/TypeTopology/blob/master/CONTRIBUTING.md).

Fix indentation sizes in `TotallySeparated.lagda`

---

source/Iterative/Ordinals-more.lagda

Prove the main lemma in Ordinals-more

---

source/Iterative/Ordinals-Addendum.lagda
source/Iterative/Sets.lagda
source/UF/Miscelanea.lagda

Also updated the comments on Ord being a retract of the type of iterative sets.

The type of iterative sets is a retract of the type of multisets

---

source/InjectiveTypes/InhabitedTypesTaboo.lagda

The type of non-empty types is injective

---

README.md
source/Integers/Abs.lagda
source/Integers/Order.lagda
source/Naturals/AbsoluteDifference.lagda
source/Naturals/Order.lagda
source/Naturals/index.lagda

I've went ahead and addressed the indentation issues pointed out by @martinescardo and did some minor polishing of the code. I also reformatted the explanation paragraphs for length and dated my contributions, and finally added myself to README.md

some cleanup to meet style guidelines

---

source/Naturals/AbsoluteDifference.lagda
source/Naturals/Order.lagda

I expanded upon my Absolute Difference module, refactored to explicitly specify used lemmas from other modules, and added one lemma to the Order file.

Absolute Difference lemmas and refactoring

---

source/DomainTheory/Basics/Pointed.lagda
source/InjectiveTypes/PointedDcpos.lagda
source/InjectiveTypes/index.lagda

@martinescardo As discussed this morning.

Carriers of pointed dcpos are algebraically injective

---

README.md
source/UF/H-Levels.lagda
source/UF/index.lagda

I also added my name to the read me file here. Hope that is okay.

Adding an alternative formulation of H-levels

---

source/Modal/Open.lagda
source/Modal/index.lagda

I wrote out the basic definitions and results for open modalities. The idea is to use this for absoluteness of compactness (to get propositional Tychonoff as a special case). However, it might be handy to have open modalities anyway so I thought it made more sense to add them to the Modal section of the library.
This pull request is just for the open modalities - I'll put the application to the absoluteness of compactness as a separate request.

Open modalities

---

source/TypeTopology/AbsolutenessOfCompactness.lagda
source/TypeTopology/AbsolutenessOfCompactnessExample.lagda

a few minor changes, as we discussed

Minor changes to absoluteness of compactness

---

source/Various/Pataraia-Taylor.lagda

This currently repeats a lot of code, but it confirms that we do get the induction principle predicatively.

Pataraia induction

---

source/Locales/DiscreteLocale/Definition.lagda
source/Locales/DiscreteLocale/Two.lagda
source/Locales/index.lagda

This PR adds a definition of the discrete locale over a set, and it also defines the locale 2 as an instance.

Define the discrete locale over a set

---

source/DomainTheory/index.lagda

Fix Issue 263

---

source/NotionsOfDecidability/Decidable.lagda

Add proof of the fact that disjunction preserves decidability

---

README.md
source/OrderedTypes/ZornsLemma.lagda
source/OrderedTypes/index.lagda
source/UF/ClassicalLogic.lagda

A proof that the Axiom of Choice implies Zorn's Lemma.
Should close or at least partially address issue #178 . Does not provide a proof that Zorn's Lemma (+ LEM) implies the Axiom of choice.
This is my first time contributing here (or really doing a substantial formalization project...), so let me know if there are any issues with choice of definitions/style!

Proof of Zorn's lemma

---

source/Lifting/Miscelanea-PropExt-FunExt.lagda
source/NotionsOfDecidability/Decidable.lagda
source/NotionsOfDecidability/DecidableClassifier.lagda
source/UF/EquivalenceExamples.lagda

This was left unformalized from my thesis: `𝓛 X ≃ (𝟙 + X) iff EM holds`.
As an auxiliary result, I also formalized that: `𝟚 ≃ Ω iff EM holds` (obvious, of course).

Lifting in the presence of excluded middle

---

source/DomainTheory/Basics/Dcpo.lagda
source/DomainTheory/Basics/LeastFixedPoint.lagda
source/DomainTheory/Basics/Miscelanea.lagda

I'll merge this basic PR myself.

Basics on omega-chains

---

source/UF/Singleton-Properties.lagda

@IanRay11 as promised.
@martinescardo I searched for this with `grep`, but couldn't find it. Happy to be corrected however :slightly_smiling_face:

The type of equivalences between two singletons is itself a singleton

---

source/MLTT/List.lagda
source/UF/DiscreteAndSeparated.lagda

Correct a mistake and add decidable-inhabited-types-are-pointed

---

source/UF/Embeddings.lagda

Type equivalences embeds into the type of functions.

Adding embedding result

---

source/UF/Truncations.lagda

I wanted to get this PR open. @tomdjong I'll let you know when it's ready for review.

H-level Truncations 

---

source/Locales/ThesisIndex.lagda
source/Locales/index.lagda

This PR creates a file `Locales.ThesisIndex` which will be used to link the thesis to the locale theory formalization.

Create index file for the thesis

---

source/UF/ConnectedTypes.lagda
source/UF/EquivalenceExamples.lagda
source/UF/TruncatedTypes.lagda
source/UF/Truncations.lagda

I have sperated out the changes to existing files from the previous PR for review, checked for unused imports and updated modification dates.

Lemmas for formalizations of results on Small Types and Connectedness

---

source/DomainTheory/Continuous-and-algebraic-domains.lagda
source/DomainTheory/Part-I.lagda
source/DomainTheory/Part-II.lagda
source/DomainTheory/index.lagda

Index for our revised domain theory paper

---

source/DomainTheory/BasesAndContinuity/Continuity.lagda
source/DomainTheory/Basics/Miscelanea.lagda
source/UF/Equiv-FunExt.lagda

I'd be happy to get your comments @martinescardo. Thanks!

Characterization of equality of (continuous) dcpos

---

README.md
source/MLTT/List-Properties.lagda
source/MLTT/List.lagda
source/Ordinals/AdditionProperties.lagda
source/Ordinals/Exponentiation/DecreasingList.lagda
source/Ordinals/Exponentiation/DecreasingListProperties-Concrete.lagda
source/Ordinals/Exponentiation/Grayson.lagda
source/Ordinals/Exponentiation/Paper.lagda
source/Ordinals/Exponentiation/PropertiesViaTransport.lagda
source/Ordinals/Exponentiation/RelatingConstructions.lagda
source/Ordinals/Exponentiation/Specification.lagda
source/Ordinals/Exponentiation/Supremum.lagda
source/Ordinals/Exponentiation/Taboos.lagda
source/Ordinals/Exponentiation/TrichotomousLeastElement.lagda
source/Ordinals/Exponentiation/index.lagda
source/Ordinals/Notions.lagda
source/Ordinals/OrdinalOfOrdinals.lagda
source/Ordinals/WellOrderArithmetic.lagda
source/Ordinals/WellOrderTransport.lagda

I'm just making a PR for the record, but I'll merge this myself.
The changes reflect the revised version of our paper _Ordinal Exponentiation in Homotopy Type Theory_ which will be uploaded to [arXiv](https://arxiv.org/abs/2501.14542) soon and will appear at [LICS 2025](https://lics.siglog.org/lics25/). In particular, we discuss and formalized a construction due to [Robin J. Grayson](https://doi.org/10.1002/malq.19820283304).

Update on ordinal exponentiation

---

source/InjectiveTypes/WeakFactorizationSystem.lagda
source/InjectiveTypes/index.lagda
source/index.lagda

@martinescardo As discussed this morning. Comments are welcome!

Initial observations on a wfs of embeddings and fiberwise injective maps

---

source/InjectiveTypes/InhabitedTypesTaboo.lagda
source/InjectiveTypes/MathematicalStructures.lagda
source/InjectiveTypes/Subtypes.lagda

I'm not sure it's worth keeping, but the easiest way to discuss it was to make a PR.

Alternative proof that the type of nonempty types is injective

---

source/UF/Pushouts.lagda

Record asserting the existence of pushouts of arbitrary spans
